let adjective = "fierce";
let noun = "dragon";
let verb = "angry";
let place = "volcano";
let adjective2 = "fiery";
let noun2 = "marshmallows";
let firstStory = "Once upon a time, there was a(n) " + adjective + " " + noun + " who loved to eat " + noun2 + ". The " + noun + " lived in a " + place + " and had " + adjective2 + " nostrils that blew fire when it was " + verb + ".";
console.log("First story: " + firstStory);
adjective = "silly";
noun = "unicorn";
verb = "tickled";
place = "rainbow forest";
adjective2 = "sparkly";
noun2 = "cupcakes";
let secondStory = "Once upon a time, there was a(n) " + adjective + " " + noun + " who loved to eat " + noun2 + ". The " + noun + " lived in a " + place + " and had " + adjective2 + " nostrils that blew fire when it was " + verb + ".";
console.log("Second story: " + secondStory);